notifications:
  email: false

language: go

go:
  - 1.14.x

services:
  - docker
#  - redis-server // the local:exec runner starts redis as a Docker container.

env:
  global:
    - GOTFLAGS="-race -coverprofile=coverage.txt -covermode=atomic"
    - GO111MODULE=on

cache:
  directories:
    - $HOME/gopath/pkg/mod

jobs:
  include:
    - stage: "lint, build, test"
      os: linux
      name: "tidy and lint"
      script:
        - make tidy
        - git diff --exit-code
        - pushd .. && go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.23.6 && popd && make lint
    - name: "build recursive, build docker & test recursive"
      os: linux
      script:
        - mkdir -p $HOME/testground/plans && ln -s $TRAVIS_BUILD_DIR/plans/placebo $HOME/testground/plans/placebo
        - make build-all
        - make docker
        - make test
    - name: "build on windows"
      os: windows
      script:
        - go build ./...
