apiVersion: apps/v1
kind: Deployment
metadata:
  name: testground-sync-service
spec:
  selector:
    matchLabels:
      name: testground-sync-service
  template:
    metadata:
      labels:
        name: testground-sync-service
    spec:
      terminationGracePeriodSeconds: 10
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: testground-sync-service
          image: iptestground/sync-service:no-redis
          command: ["/service"]
          env:
            - name: REDIS_HOST
              value: "172.18.0.1"
          ports:
            - name: syncservicehttp
              containerPort: 5050
          resources:
            limits:
              cpu: 20m
              memory: 26Mi
            requests:
              cpu: 20m
              memory: 26Mi
      nodeSelector:
        testground.node.role.plan: "true"
