name = "bitswap-tuning"
# hashicorp/go-getter URLs, so in the future we can support fetching test plans
# from GitHub.
source_path = "file:${TESTGROUND_SRCDIR}/plans/bitswap-tuning"

[defaults]
builder = "docker:go"
runner = "local:docker"

[build_strategies."docker:go"]
enabled = true
go_version = "1.13"
module_path = "github.com/ipfs/testground/plans/bitswap-tuning"
exec_pkg = "."

# TODO: exec:go is not ready yet
[build_strategies."exec:go"]
enabled = true
module_path = "github.com/ipfs/testground/plans/bitswap-tuning"
exec_pkg = "."

[run_strategies."local:docker"]
enabled = true

[run_strategies."local:exec"]
enabled = true

[run_strategies."cluster:swarm"]
enabled = true

# seq 0
[[testcases]]
name = "transfer"
instances = { min = 2, max = 64, default = 2 }

  [testcases.params]
  leech_count = { type = "int", desc = "number of leech nodes", unit = "peers", default = 1 }
  passive_count = { type = "int", desc = "number of passive nodes (neither leech nor seed)", unit = "peers", default = 0 }
  timeout_secs = { type = "int", desc = "timeout", unit = "seconds", default = 60 }
  request_stagger = { type = "int", desc = "time between each leech's first request", unit = "ms", default = 0}
  file_size = { type = "int", desc = "file size", unit = "bytes", default = 4194304 }
  latency_ms = { type = "int", desc = "latency", unit = "ms", default = 5 }
  bandwidth_mb = { type = "int", desc = "bandwidth", unit = "Mib", default = 1024 }
