name = "dht"
# hashicorp/go-getter URLs, so in the future we can support fetching test plans
# from GitHub.
source_path = "file:${TESTGROUND_SRCDIR}/plans/dht"

[build_strategies."docker:go"]
enabled = true
go_version = "1.13"
module_path = "github.com/ipfs/testground/plans/dht"
exec_pkg = "."

# TODO: exec:go is not ready yet
[build_strategies."exec:go"]
enabled = true
module_path = "github.com/ipfs/testground/plans/dht"
exec_pkg = "."

[run_strategies."local:docker"]
enabled = true

# TODO: local:exec is not ready yet
[run_strategies."local:exec"]
enabled = true

# TODO: local:exec is not ready yet
[run_strategies."cluster:nomad"]
enabled = true

# seq 0
[[testcases]]
name = "lookup-peers"
instances = { min = 2, max = 100, default = 50 }

  [testcases.params]
  bucket_size = { type = "int", desc = "bucket size", unit = "peers" }
  timeout_secs = { type = "int", desc = "timeout", unit = "seconds"}

# seq 1
[[testcases]]
name = "lookup-providers"
instances = { min = 2, max = 100, default = 50 }

  [testcases.params]
  bucket_size = { type = "int", desc = "bucket size", unit = "peers" }

# seq 2
[[testcases]]
name = "store-get-value"
instances = { min = 2, max = 100, default = 50 }
roles = ["storer", "fetcher"]

  [testcases.params]
  bucket_size = { type = "int", desc = "bucket size", unit = "peers" }
