- hosts: all
  become: true
  gather_facts: false
  roles:
  # Prepare system to be managed by Ansible.
  - role: robertdebock.bootstrap
    bootstrap_user: "{{ ansible_user }}"
    bootstrap_retries: 3
    bootstrap_wait_for_host: yes
    tags: [bootstrap]
  # Set hostname
  - role: setup
    tags: [setup]
  # Docker
  - role: geerlingguy.docker
    tags: [docker]
  - role: geerlingguy.pip
    pip_install_packages:
    - name: docker
    tags: [pip]
  - role: docker-cleanup
    tags: [docker-cleanup]
  # Filebeat
  - role: filebeat
    tags: [filebeat]
  # Log rotation
  - role: nickhammond.logrotate
    logrotate_scripts:
    - name: docker-containers
      path: /var/lib/docker/containers/*/*.log
      options:
        - daily
        - size 100M
        - rotate 4
        - missingok
        - copytruncate
        - nodateext
        - maxage 5
    tags: [logrotate]

- hosts: role_manager
  name: Initialise Docker Swarm cluster
  become: true
  gather_facts: true
  roles:
    - swarm-init
  tags: [managers]

- hosts: role_worker
  name: Join workers to Docker Swarm cluster
  become: true
  gather_facts: false
  vars:
      token: "{{ hostvars[groups['role_manager'][0]]['worker_token']['stdout'] }}"
      manager: "{{ hostvars[groups['role_manager'][0]]['manager_ipv4']['stdout'] }}"
  roles:
    - swarm-join
  tags: [workers]

- hosts: role_redis
  name: Join Redis to Docker Swarm cluster
  become: true
  gather_facts: true
  vars:
      token: "{{ hostvars[groups['role_manager'][0]]['worker_token']['stdout'] }}"
      manager: "{{ hostvars[groups['role_manager'][0]]['manager_ipv4']['stdout'] }}"
  roles:
    - swarm-join
  tags: [redis-join]

- hosts: role_manager
  name: Label Docker Swarm worker nodes and Install Testground services
  become: true
  gather_facts: true
  roles:
    - swarm-label
    - testground-services

- hosts: role_worker
  name: Run sidecar container on every worker node
  become: true
  gather_facts: true
  roles:
    - testground-sidecar
