name = "example-js"

[defaults]
builder = "docker:generic"
runner = "local:docker"

[builders."docker:generic"]
enabled = true

[runners."local:docker"]
enabled = true

[[testcases]]
name = "failure"
instances = { min = 1, max = 200, default = 1 }

[[testcases]]
name = "output"
instances = { min = 1, max = 200, default = 1 }

[[testcases]]
name = "sync"
instances = { min = 2, max = 200, default = 2 }

[[testcases]]
name = "pingpong"
instances = { min = 1, max = 200, default = 1 }
