apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: ${NAME}
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: ${KOPS_STATE_STORE}/${NAME}
  docker:
    defaultUlimit:
    - "nofile=${ULIMIT_NOFILE}"
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-${ZONE}
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-${ZONE}
      name: a
    memoryRequest: 100Mi
    name: events
  hooks:
    - name: disable-transparent-hugepages.service
      before:
      - docker.service
      - kubelet.service
      manifest: |
        Type=oneshot
        ExecStart=/bin/sh -c "echo never >/sys/kernel/mm/transparent_hugepage/enabled"
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
    maxPods: 200
    allowedUnsafeSysctls:
      - net.netfilter.nf_conntrack_max
      - net.core.somaxconn
      - net.core.netdev_max_backlog
      - net.core.rmem_max
      - net.core.wmem_max
      - net.ipv4.ip_local_port_range
      - net.ipv4.tcp_max_syn_backlog
      - net.ipv4.tcp_tw_recycle
      - net.ipv4.tcp_tw_reuse
      - net.ipv4.tcp_mem
      - net.ipv4.tcp_rmem
      - net.ipv4.tcp_wmem
      - net.ipv4.tcp_max_orphans
      - net.ipv4.tcp_abort_on_overflow
    streamingConnectionIdleTimeout: 60m
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.17.3
  masterInternalName: api.internal.${NAME}
  masterPublicName: api.${NAME}
  networkCIDR: 172.20.0.0/16
  networking:
    flannel:
      backend: vxlan
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: ${ZONE}
    type: Public
    zone: ${ZONE}
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: ${NAME}
  name: master-${ZONE}
spec:
  additionalUserData:
  - name: myscript.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      cat <<EOT >> /etc/sysctl.d/999-testground.conf
      net.core.somaxconn = 131072
      net.netfilter.nf_conntrack_max = 1048576
      net.ipv4.tcp_max_syn_backlog = 131072
      net.core.netdev_max_backlog = 524288
      net.ipv4.ip_local_port_range = 1024 65535
      net.ipv4.tcp_tw_recycle = 1
      net.ipv4.tcp_tw_reuse = 1
      net.core.rmem_max = 131072
      net.core.wmem_max = 131072
      net.ipv4.tcp_mem = 262144 524288 1048576
      net.ipv4.tcp_rmem = 4096 65536 131072
      net.ipv4.tcp_wmem = 4096 65536 131072
      EOT
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: c5.2xlarge
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-${ZONE}
  role: Master
  subnets:
  - ${ZONE}

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: ${NAME}
  name: nodes
spec:
  additionalUserData:
  - name: myscript.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      cat <<EOT >> /etc/sysctl.d/999-testground.conf
      net.core.somaxconn = 131072
      net.netfilter.nf_conntrack_max = 1048576
      net.ipv4.tcp_max_syn_backlog = 131072
      net.core.netdev_max_backlog = 524288
      net.ipv4.ip_local_port_range = 1024 65535
      net.ipv4.tcp_tw_recycle = 1
      net.ipv4.tcp_tw_reuse = 1
      net.core.rmem_max = 131072
      net.core.wmem_max = 131072
      net.ipv4.tcp_mem = 262144 524288 1048576
      net.ipv4.tcp_rmem = 4096 65536 131072
      net.ipv4.tcp_wmem = 4096 65536 131072
      EOT
  cloudLabels:
    testground.nodetype: plan
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: c5.2xlarge
  maxSize: ${WORKER_NODES}
  minSize: ${WORKER_NODES}
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
    testground.nodetype: plan
  role: Node
  subnets:
  - ${ZONE}

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: ${NAME}
  name: tginfra
spec:
  additionalUserData:
  - name: myscript.sh
    type: text/x-shellscript
    content: |
      #!/bin/sh
      cat <<EOT >> /etc/sysctl.d/999-testground.conf
      net.core.somaxconn = 100000
      net.ipv4.tcp_max_syn_backlog = 100000
      net.core.netdev_max_backlog = 100000
      net.ipv4.ip_local_port_range = 1024 65535
      net.ipv4.tcp_tw_recycle = 1
      net.ipv4.tcp_tw_reuse = 1
      net.core.rmem_max = 134217728
      net.core.wmem_max = 134217728
      net.ipv4.tcp_rmem = 4096 12582912 67108864
      net.ipv4.tcp_wmem = 4096 12582912 67108864
      EOT
  cloudLabels:
    testground.nodetype: infra
  image: kope.io/k8s-1.17-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: c5.2xlarge
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: tginfra
    testground.nodetype: infra
  role: Node
  subnets:
  - ${ZONE}
