[metadata]
  name = "find-provs"
  author = "adin"

[global]
  plan = "dht"
  case = "find-providers"
  total_instances = 100
  builder = "docker:go"
  runner = "cluster:k8s"
  [global.build_config]
    push_registry = true
    registry_type = "aws"
  [global.run_config]
    keep_service = true

[[groups]]
  id = "balsam-undialable-provider"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:b40b3e74684f"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "4"
      record_count = "1"
      search_records = "true"
      timeout_secs = "200"
      undialable = "true"

[[groups]]
  id = "balsam-undialable-searcher"
  [groups.instances]
    count = 35
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:337d6d32837a"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "4"
      search_records = "true"
      timeout_secs = "200"
      undialable = "true"

[[groups]]
  id = "balsam-dialable-provider"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:6a550c1098e6"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "4"
      record_count = "1"
      timeout_secs = "200"
      undialable = "false"

[[groups]]
  id = "balsam-dialable-searcher"
  [groups.instances]
    count = 35
    percentage = 0.0
  [groups.build]
    Selectors = ["balsam"]
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:75f6df08d8ca"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "4"
      search_records = "true"
      timeout_secs = "200"
      undialable = "false"

[[groups]]
  id = "cypress-provider"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "v0.5.2-0.20200313220425-e42ee9421469"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-autonat"
      version = "v0.1.2-0.20200311232101-4cd130cbe2f9"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-autonat-svc"
      version = "v0.1.1-0.20200316084915-0eaa5cdf304b"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p"
      version = "v0.6.1-0.20200310185355-89c193e0ca37"
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:fbb54cf68859"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "4"
      record_count = "1"
      timeout_secs = "200"

[[groups]]
  id = "cypress-searcher"
  [groups.instances]
    count = 10
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "v0.5.2-0.20200313220425-e42ee9421469"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-autonat"
      version = "v0.1.2-0.20200311232101-4cd130cbe2f9"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-autonat-svc"
      version = "v0.1.1-0.20200316084915-0eaa5cdf304b"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p"
      version = "v0.6.1-0.20200310185355-89c193e0ca37"
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:627b4b7dd7e6"
    [groups.run.test_params]
      bs_strategy = "3"
      bucket_size = "4"
      search_records = "true"
      timeout_secs = "200"

[[groups]]
  id = "cypress-bs"
  [groups.instances]
    count = 5
    percentage = 0.0
  [groups.build]
    Selectors = ["cypress"]

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-kad-dht"
      version = "v0.5.2-0.20200313220425-e42ee9421469"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-autonat"
      version = "v0.1.2-0.20200311232101-4cd130cbe2f9"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p-autonat-svc"
      version = "v0.1.1-0.20200316084915-0eaa5cdf304b"

    [[groups.build.dependencies]]
      module = "github.com/libp2p/go-libp2p"
      version = "v0.6.1-0.20200310185355-89c193e0ca37"
  [groups.run]
    artifact = "909427826938.dkr.ecr.us-east-1.amazonaws.com/testground-us-east-1-dht:38fd7a90fb28"
    [groups.run.test_params]
      bootstrapper = "true"
      bs_strategy = "1"
      bucket_size = "4"
      timeout_secs = "200"
