## Building this composition of 40 groups should only trigger 4 unique builds.

[metadata]
name = "unique-builds"
author = "raulk"

[global]
plan = "example"
case = "sync"
total_instances = 40

builder = "exec:go"
runner = "local:exec"

[[groups]]
id = "group00"
instances = { count = 1 }

[[groups]]
id = "group01"
instances = { count = 1 }

[[groups]]
id = "group02"
instances = { count = 1 }

[[groups]]
id = "group03"
instances = { count = 1 }

[[groups]]
id = "group04"
instances = { count = 1 }

[[groups]]
id = "group05"
instances = { count = 1 }

[[groups]]
id = "group06"
instances = { count = 1 }

[[groups]]
id = "group07"
instances = { count = 1 }

[[groups]]
id = "group08"
instances = { count = 1 }

[[groups]]
id = "group09"
instances = { count = 1 }

########

[[groups]]
id = "group10"
instances = { count = 1 }

[groups.build]
selectors = ["foo"]
dependencies = [
    { module = "github.com/testground/module-a", version = "v0.0.1"}
]

[[groups]]
id = "group11"
instances = { count = 1 }

[groups.build]
selectors = ["foo"]
dependencies = [
    { module = "github.com/testground/module-a", version = "v0.0.1"}
]

[[groups]]
id = "group12"
instances = { count = 1 }

[groups.build]
selectors = ["foo"]
dependencies = [
    { module = "github.com/testground/module-a", version = "v0.0.1"}
]

[[groups]]
id = "group13"
instances = { count = 1 }

[groups.build]
selectors = ["foo"]
dependencies = [
    { module = "github.com/testground/module-a", version = "v0.0.1"}
]

[[groups]]
id = "group14"
instances = { count = 1 }

[groups.build]
selectors = ["foo"]
dependencies = [
    { module = "github.com/testground/module-a", version = "v0.0.1"}
]

[[groups]]
id = "group15"
instances = { count = 1 }

[groups.build]
selectors = ["foo"]
dependencies = [
    { module = "github.com/testground/module-a", version = "v0.0.1"}
]

[[groups]]
id = "group16"
instances = { count = 1 }

[groups.build]
selectors = ["foo"]
dependencies = [
    { module = "github.com/testground/module-a", version = "v0.0.1"}
]

[[groups]]
id = "group17"
instances = { count = 1 }

[groups.build]
selectors = ["foo"]
dependencies = [
    { module = "github.com/testground/module-a", version = "v0.0.1"}
]

[[groups]]
id = "group18"
instances = { count = 1 }

[groups.build]
selectors = ["foo"]
dependencies = [
    { module = "github.com/testground/module-a", version = "v0.0.1"}
]

[[groups]]
id = "group19"
instances = { count = 1 }

[groups.build]
selectors = ["foo"]
dependencies = [
    { module = "github.com/testground/module-a", version = "v0.0.1"}
]

########

[[groups]]
id = "group20"
instances = { count = 1 }

[groups.build]
selectors = ["bar"]
dependencies = [
    { module = "github.com/testground/module-b", version = "v1.0.0"}
]

[[groups]]
id = "group21"
instances = { count = 1 }

[groups.build]
selectors = ["bar"]
dependencies = [
    { module = "github.com/testground/module-b", version = "v1.0.0"}
]

[[groups]]
id = "group22"
instances = { count = 1 }

[groups.build]
selectors = ["bar"]
dependencies = [
    { module = "github.com/testground/module-b", version = "v1.0.0"}
]

[[groups]]
id = "group23"
instances = { count = 1 }

[groups.build]
selectors = ["bar"]
dependencies = [
    { module = "github.com/testground/module-b", version = "v1.0.0"}
]

[[groups]]
id = "group24"
instances = { count = 1 }

[groups.build]
selectors = ["bar"]
dependencies = [
    { module = "github.com/testground/module-b", version = "v1.0.0"}
]

[[groups]]
id = "group25"
instances = { count = 1 }

[groups.build]
selectors = ["bar"]
dependencies = [
    { module = "github.com/testground/module-b", version = "v1.0.0"}
]

[[groups]]
id = "group26"
instances = { count = 1 }

[groups.build]
selectors = ["bar"]
dependencies = [
    { module = "github.com/testground/module-b", version = "v1.0.0"}
]

[[groups]]
id = "group27"
instances = { count = 1 }

[groups.build]
selectors = ["bar"]
dependencies = [
    { module = "github.com/testground/module-b", version = "v1.0.0"}
]

[[groups]]
id = "group28"
instances = { count = 1 }

[groups.build]
selectors = ["bar"]
dependencies = [
    { module = "github.com/testground/module-b", version = "v1.0.0"}
]

[[groups]]
id = "group29"
instances = { count = 1 }

[groups.build]
selectors = ["bar"]
dependencies = [
    { module = "github.com/testground/module-b", version = "v1.0.0"}
]

########

[[groups]]
id = "group30"
instances = { count = 1 }

[groups.build]
selectors = ["foo"]

[[groups]]
id = "group31"
instances = { count = 1 }

[groups.build]
selectors = ["foo"]

[[groups]]
id = "group32"
instances = { count = 1 }

[groups.build]
selectors = ["foo"]

[[groups]]
id = "group33"
instances = { count = 1 }

[groups.build]
selectors = ["foo"]

[[groups]]
id = "group34"
instances = { count = 1 }

[groups.build]
selectors = ["foo"]

[[groups]]
id = "group35"
instances = { count = 1 }

[groups.build]
selectors = ["foo"]

[[groups]]
id = "group36"
instances = { count = 1 }

[groups.build]
selectors = ["foo"]

[[groups]]
id = "group37"
instances = { count = 1 }

[groups.build]
selectors = ["foo"]

[[groups]]
id = "group38"
instances = { count = 1 }

[groups.build]
selectors = ["foo"]

[[groups]]
id = "group39"
instances = { count = 1 }

[groups.build]
selectors = ["foo"]
