name = "placebo"

[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."nix:generic"]
enabled = true

[builders."docker:go"]
enabled = true

[builders."exec:go"]
enabled = true

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:swarm"]
enabled = true

[[testcases]]
name = "ok"
instances = { min = 1, max = 200, default = 1 }

  [testcases.params]
  some_param = { type = "int", desc = "some param", unit = "peers" }

[[testcases]]
name = "abort"
instances = { min = 1, max = 250, default = 1 }

  [testcases.params]
  some_param = { type = "int", desc = "some param", unit = "peers" }

[[testcases]]
name = "metrics"
instances = { min = 1, max = 250, default = 1 }

  [testcases.params]
  some_param = { type = "int", desc = "some param", unit = "peers" }

[[testcases]]
name = "panic"
instances = { min = 1, max = 250, default = 1 }

[[testcases]]
name = "stall"
instances = { min = 1, max = 250, default = 1 }
