apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dummy
  namespace: default
  labels:
    k8s-app: dummy
spec:
  selector:
    matchLabels:
      name: dummy
  template:
    metadata:
      annotations:
        cni: "flannel"
      labels:
        name: dummy
    spec:
      volumes:
      - name: host-sys
        hostPath:
          path: /sys
      containers:
      - name: dummy
        command: ["/bin/sleep", "3650d"]
        image: governmentpaas/curl-ssl
