apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: weave-net
  labels:
    k8s-app: weave-net
  namespace: monitoring
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: weave-net
  namespaceSelector:
    matchNames:
    - kube-system
  endpoints:
  - port: weave-metrics
    path: /metrics
    interval: 5s
